#include "session/reset_env.h"

#include <algorithm>

namespace qfv {

std::string resetEnvironment(const std::string& top, const std::string& clock, const std::string& resetExpr,
                             int cycles, bool freeAfter) {
    cycles = std::max(1, std::min(cycles, 255));
    std::string s = "// Generated by qfv: reset -expression (" + resetExpr + "), " + std::to_string(cycles) +
                    " cycle(s)\n"
                    "module qfv_env (input clk, input rst_active);\n"
                    "    reg [7:0] reset_count = 8'd0;\n"
                    "    always @(posedge clk) if (reset_count != 8'd" + std::to_string(cycles) +
                    ") reset_count <= reset_count + 8'd1;\n"
                    "    always @(*) begin\n"
                    "        if (reset_count != 8'd" + std::to_string(cycles) + ") assume (rst_active);\n";
    if (!freeAfter)
        s += "        else assume (!rst_active);\n";
    s += "    end\nendmodule\n\nbind " + top + " qfv_env qfv_env_inst (.clk(" + clock + "), .rst_active(" +
         resetExpr + "));\n";
    return s;
}

} // namespace qfv
