#!/usr/bin/env python3
"""Turn a Yosys witness (.yw) counterexample into a standalone SV replay testbench.

The testbench instantiates the *original* RTL top (assertions arrive through
`bind`), loads the CEX initial state, drives the inputs cycle by cycle, and lets
the simulator's own SVA checker decide whether an assertion fails. This checks
a CEX independently of the engine that found it (SPEC.md section 8).

Usage: yw2tb.py trace.yw <top_module> <out_tb.sv>
"""
import json
import sys


def hier_name(path):
    """['\\fifo_tb_inst', '\\fifo_array', '\\[0]'] -> 'fifo_tb_inst.fifo_array[0]'"""
    name = ""
    for part in path:
        part = part.lstrip("\\")
        if part.startswith("["):
            name += part
        else:
            name += ("." if name else "") + part
    return name


def signal_values(signals, bits):
    """Yosys witness bit strings are LSB-last: bit 0 of the step is the last char."""
    lsb_first = bits[::-1]
    offset = 0
    values = {}
    for sig in signals:
        chunk = lsb_first[offset:offset + sig["width"]]
        offset += sig["width"]
        if len(chunk) == sig["width"]:
            # '?' marks a don't-care bit: the CEX holds for any value, so pick 0.
            values[hier_name(sig["path"])] = chunk[::-1].replace("?", "0")  # MSB-first
    return values


def main(yw_path, top, out_path):
    yw = json.load(open(yw_path))
    clocks = {hier_name(c["path"]) for c in yw.get("clocks", [])}
    inputs = [s for s in yw["signals"] if not s["init_only"]]
    states = [s for s in yw["signals"] if s["init_only"]]
    input_names = [hier_name(s["path"]) for s in inputs if hier_name(s["path"]) not in clocks]
    clock = next(iter(clocks), "clk")

    lines = [f"// Generated by yw2tb.py from {yw_path}", "module qfv_replay;"]
    lines.append(f"  reg {clock} = 0;")
    for s in inputs:
        n = hier_name(s["path"])
        if n != clock:
            lines.append(f"  reg [{s['width'] - 1}:0] {n};")
    ports = ", ".join(f".{n}({n})" for n in [clock] + input_names)
    lines.append(f"  {top} dut ({ports});")
    lines.append("  initial begin")

    steps = yw["steps"]
    init = signal_values(yw["signals"], steps[0]["bits"])
    for s in states:
        n = hier_name(s["path"])
        # Yosys-internal state ($auto$..., e.g. from async2sync/chformal) has no
        # RTL counterpart; the replay checks the RTL, so only RTL state is set.
        if n in init and "$" not in n:
            lines.append(f"    dut.{n} = {s['width']}'b{init[n]};")
    for i, step in enumerate(steps):
        vals = signal_values(inputs, step["bits"])
        drive = " ".join(f"{n} = {len(vals[n])}'b{vals[n]};" for n in input_names if n in vals)
        lines.append(f"    // cycle {i}")
        lines.append(f"    {drive}")
        lines.append(f"    #5 {clock} = 1; #5 {clock} = 0;")
    lines.append(f'    $display("QFV_REPLAY_END cycles={len(steps)}");')
    lines.append("    $finish;")
    lines.append("  end")
    lines.append("endmodule")
    open(out_path, "w").write("\n".join(lines) + "\n")


if __name__ == "__main__":
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    main(*sys.argv[1:])
